### ISSUE TITLE
astra voice agent's memory keeps increasing during startup and eventually leads to a crash

### ISSUE THREAD

**Issue by Sam-SSTU** [TEN-framework/ASTRA.ai#215]
windows11 pro
docker
astra voice agent

when met this problem, the only thing that I can do is to restart my computer and rebuild, pretty annoying

**Comment by Sam-SSTU** [comment]
100%复现情况为openai_chatgpt_extension.py文件有错误时，是不是应该在有错误时报错或者Break掉？

**Comment by plutoless** [comment]
the exit logic has been optimized in https://github.com/TEN-framework/ASTRA.ai/pull/242
