### ISSUE TITLE
on_pcm_frame() still in extension.py created by tman 

### ISSUE THREAD

**Issue by Huangshan16** [TEN-framework/ASTRA.ai#227]
**Describe the bug**
on_pcm_frame() still in extension.py created by tman 

**To Reproduce**
1. Go to 'src created by tman'
2. Click on 'extension.py'
3. Scroll down to 'line 57'

**Expected behavior**
on_pcm_frame() -> on_audio_frame()

**Screenshots**
![image](https://github.com/user-attachments/assets/35295eaf-dc47-44c6-b03e-1bc57a2970c7)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [arc]
 - Version [0.4.0]

**Comment by wangyoucao577** [comment]
Fixed version has been published, close it.
